export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'body-max-line-length': [0, 'always', 0],
    'scope-enum': [
      2,
      'always',
      [
        'popup',
        'options',
        'background',
        'content',
        'wizard',
        'strategies',
        'overlay',
        'progress',
        'image-pick',
        'shared',
        'messaging',
        'storage',
        'api-client',
        'auth-flow',
        'manifest',
        'deps',
        'config',
        'ci',
        'release',
        'docs',
      ],
    ],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'refactor',
        'perf',
        'docs',
        'style',
        'chore',
        'test',
        'ci',
        'revert',
      ],
    ],
  },
};
